Repository opaque-systems/opaqueprompts-chat-server, pull requests merged in 2023-09, with the labels that each got.

#32 refactor: Use Environment Variables to configure Auth0 Domain and Au…
  .github/workflows/tests.yaml
  python-package/src/opchatserver/authorization.py
  python-package/src/opchatserver/server.py
Labels: refactor

#35 build: use upstream langchain
  python-package/requirements.txt
Labels: build

#33 docs: add new environment variables to sample `docker run` command
  docker/README.md
Labels: docs

#36 test: Fix test_verify_scope unit test
  python-package/tests/unit/test_authorization.py
Labels: test

#37 docs: Add link to LangChain docs in code
  python-package/src/opchatserver/server.py
Labels: docs

#38 feat: change the openai model
  python-package/README.md
  python-package/src/opchatserver/server.py
Labels: feat

#39 build: bump opaqueprompts to 0.0.6
  python-package/requirements.txt
Labels: build
